[package]
name = "balls"
version = "0.1.0"
authors = ["horup <sah@sah.dk>"]
edition = "2018"


[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
frameworky = { path = "../.." }
wasm-bindgen = "0.2.68"