name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Deploy WASM
      run: |
        cargo install wasm-pack
        wasm-pack build examples/balls --target web

        git add -f examples/balls/pkg
        git stash

        git checkout --track origin/pages
        git rm examples/balls/pkg -r
        git add .
        git commit -m "cleanup"
        git stash pop
        git commit -m "updated"
        git checkout master
        echo done
      
