name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Examples
      run: cargo build --example balls --release
    - uses: actions/upload-artifact@v2
      with: 
        name: balls
        path: target/release/examples/balls.exe
      
